### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by Selucote82** [rrwick/Unicycler#245] opened 2020-08-19 17:12 UTC
Hi all,
first of all, excuse me if the problem was solved in precedent issues, but I only saw the issue #104 tackling the same error.

This error I got after launching unicycler with the following dependencies:

Dependencies:
  Program         Version           Status
  spades.py       3.11.1            good
  racon           1.4.16            good
  makeblastdb     2.2.30+           good
  tblastn         2.2.30+           good
  bowtie2-build   2.3.4.1           good
  bowtie2         2.3.4.1           good
  samtools        1.6               good
  java            11.0.1-internal   good
  pilon           1.23              good
  bcftools                          not used

The complete error:

Traceback (most recent call last):
  File "/home/software/unicycler/bin/unicycler", line 11, in <module>
    load_entry_point('unicycler==0.4.9b0', 'console_scripts', 'unicycler')()
  File "/home/software/python-3.8.2/lib/python3.8/site-packages/unicycler/unicycler.py", line 162, in main
    bridges += create_simple_long_read_bridges(graph, args.out, args.keep, args.threads,
  File "/home/software/python-3.8.2/lib/python3.8/site-packages/unicycler/bridge_long_read_simple.py", line 131, in create_simple_long_read_bridges
    bridges += simple_bridge_loops(graph, start_overlap_reads, end_overlap_reads,
  File "/home/software/python-3.8.2/lib/python3.8/site-packages/unicycler/bridge_long_read_simple.py", line 355, in simple_bridge_loops
    for loop_count in sorted(votes.keys()):
TypeError: '<' not supported between instances of 'NoneType' and 'int'

As I have been able to see in google, it seems to be related with the version of python. Also the break occurred in the same point than in the issue #104, as you can see in the attached file, but I tried some different options, former racon versions and also disabling this software, and the error appeared likewise. Could you be so kind as to help me?

Thank you.
[unicycler.salida.txt](https://github.com/rrwick/Unicycler/files/5097942/unicycler.salida.txt)

**Comment by rrwick** [comment] 2022-01-21 01:40
I'm working on a new version of Unicycler (v0.5.0), and I think I see the cause of this bug, which I've hopefully now fixed (05ea9bd). Thanks for letting me know, and sorry it took me so long to get around to this! The new version will be released in the near future.

Ryan

**Closed by rrwick** 2022-01-21 01:40 UTC
