### ISSUE TITLE
in unicycler_polish-runner.py, Racon fails because the input file is stdin rather than .sam

### ISSUE THREAD

**Issue by tuspjo** [rrwick/Unicycler#228] opened 2020-02-10 15:20 UTC
Hi, 
Thanks for making this fantastic software. 
I'm running some assemblies through the polishing module unicycler_polish-runner.py, and it fails at the "Long read polish, small variants" step, because the command 'minimap2 -t 16 006_4_polish.fasta longread.fq | racon -t 16 longread.fq - 006_4_polish.fasta 009_1_racon_polish.fasta' does not produce an output. I think that the issue is that racon does not take stdin as input and exits with the error that the input format does not have a recognized extension. 

Is there a way to fix this issue? I'm thinking to run the two commands seperately, which should not take that much extra time.

Best,

Tue

**Comment by jflot** [comment] 2020-10-20 08:14
Another issue is that the stdout of racon needs to be redirected to the racon_polish.fasta file. If I modify the two commands and run them by hand (`minimap -t 8 023_2_polish.fasta longreads.fa > tmp.paf` then `racon -t 8 longreads.fa tmp.paf 023_2_polish.fasta > 026_1_racon_polish.fasta`), it works fine. It would be great to fix this in the python code.

**Comment by barakova** [comment] 2021-02-08 10:37
Hi @tuspjo and @jflot 

I am having the same issue when racon does not produce an output. Did you solve the issue somehow? I am not very good at programming so manual fixing is very hard for me.

Thank you very much

**Comment by tuspjo** [comment] 2021-02-08 11:29
I did not find a solution, unfortunately, I now only polish using short reads, as the (flye) assembly polishes using the long reads.

**Comment by jflot** [comment] 2021-02-08 12:41
I finally managed to fix the issue by installing racon version 0.5.0 (https://github.com/isovic/racon/releases/tag/0.5.0), which was the current racon version at the time when unicycler_polish was designed.

**Comment by barakova** [comment] 2021-02-09 10:13
Thank you very much @jflot.
Older version of racon helped me but now I am having issues with nucmer. What kind of version do you have? I tried mummer 3.23 and now mummer 4 but both end up with different errors.

**Comment by jflot** [comment] 2021-05-05 20:38
Sorry for my late reply. I just checked and the version of mummer installed on the computer cluster where I am running unicycler_polish is 4.0.0rc1.
In case it helps, here is the command line I have been using:
```nohup unicycler_polish-runner.py -1 ../Illumina/short_reads_1.fastq.gz -2 ../Illumina/short_reads_2.fastq.gz --long_reads ../nanopore.fq -a polishingresult.fasta --threads 8 --pilon ~/.local/bin/ --racon ~/.local/src/racon-v0.5.0/bin/racon &```

**Comment by rrwick** [comment] 2022-01-22 04:46
I appreciate the discussion here, but as an FYI, I'm now removing `unicycler_polish` from Unicycler because I think it's quite out-of-date. So I'll close this issue now :smile:

**Closed by rrwick** 2022-01-22 04:46 UTC
