### ISSUE TITLE
No module named 'pkg_resources'

### ISSUE THREAD

**Issue by GA-Goig** [rrwick/Unicycler#15] opened 2017-05-05 10:20 UTC
Hi I have installed Unicycler on a CentOS server but when trying to execute "unicycler" it raises the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/unicycler", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named 'pkg_resources'
```

I've been trying to fix this problem several ways, including what is explained in [this StackOverflow thread](http://stackoverflow.com/questions/7446187/no-module-named-pkg-resources)
And also tried to uninstall and install again setuptools and even pip and pip3

Nothing worked for me

Greetings!

**Comment by rrwick** [comment] 2017-05-11 23:02
Hello!

This is a tough one to debug because I can't reproduce the issue myself. My first thought to troubleshoot is to see if setuptools is installed and working for your Python3 installation.

Can you launch the Python 3 interpreter with `python3` and note the version?
Then try these commands to see if they give an error:
```
import setuptools
import pkg_resources
```

Thanks!

**Comment by rrwick** [comment] 2017-10-07 02:27
This issue is a bit old, so I'm going to close it now. But I'm happy to reopen it if you're still having the problem - just let me know.

Ryan

**Closed by rrwick** 2017-10-07 02:27 UTC
