### ISSUE TITLE
Mac compilation failure - v0.4.6

### ISSUE THREAD

**Issue by nextgenusfs** [rrwick/Unicycler#132] opened 2018-08-23 02:02 UTC
Having some issues on install. 

```
$ make CXX=g++-7 CC=gcc-7
Platform: Mac
Compiler: g++ 7.3.0
g++-7 -std=c++14 -Iunicycler/include -fPIC -O3 -DNDEBUG -Wall -Wextra -pedantic -mtune=native -c -o unicycler/src/scrub.o unicycler/src/scrub.cpp
g++-7 -std=c++14 -Iunicycler/include -fPIC -O3 -DNDEBUG -Wall -Wextra -pedantic -mtune=native -c -o unicycler/src/semi_global_align.o unicycler/src/semi_global_align.cpp
In file included from /usr/local/include/assert.h:5:0,
                 from /usr/local/Cellar/gcc@7/7.3.0/include/c++/7.3.0/cassert:44,
                 from unicycler/include/seqan/sequence.h:56,
                 from unicycler/include/semi_global_align.h:15,
                 from unicycler/src/semi_global_align.cpp:12:
/usr/local/include/except.h:15:32: error: conflicting declaration 'typedef struct Except_Frame_T* Except_Frame_T'
 typedef struct Except_Frame_T *Except_Frame_T;
                                ^~~~~~~~~~~~~~
/usr/local/include/except.h:15:16: note: previous declaration as 'struct Except_Frame_T'
 typedef struct Except_Frame_T *Except_Frame_T;
                ^~~~~~~~~~~~~~
/usr/local/include/except.h:17:18: error: field 'prev' has incomplete type 'Except_Frame_T'
   Except_Frame_T prev;
                  ^~~~
/usr/local/include/except.h:16:8: note: definition of 'struct Except_Frame_T' is not complete until the closing brace
 struct Except_Frame_T {
        ^~~~~~~~~~~~~~
make: *** [unicycler/src/semi_global_align.o] Error 1
```
```
$ make CXX=clang++ CC=clang
Platform: Mac
Compiler: clang 9.1.0
clang++ -std=c++14 -Iunicycler/include -fPIC -O3 -DNDEBUG -Wall -Wextra -pedantic -mtune=native -c -o unicycler/src/scrub.o unicycler/src/scrub.cpp
In file included from unicycler/src/scrub.cpp:12:
In file included from unicycler/include/scrub.h:15:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/string:470:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/string_view:169:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/__string:56:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/algorithm:643:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/memory:656:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/cassert:21:
In file included from /usr/local/include/assert.h:5:
/usr/local/include/except.h:15:32: error: typedef redefinition with different types ('struct Except_Frame_T *' vs 'Except_Frame_T')
typedef struct Except_Frame_T *Except_Frame_T;
                               ^
/usr/local/include/except.h:15:16: note: previous definition is here
typedef struct Except_Frame_T *Except_Frame_T;
               ^
/usr/local/include/except.h:17:18: error: field has incomplete type 'Except_Frame_T'
  Except_Frame_T prev;
                 ^
/usr/local/include/except.h:16:8: note: definition of 'Except_Frame_T' is not complete until the closing '}'
struct Except_Frame_T {
       ^
2 errors generated.
make: *** [unicycler/src/scrub.o] Error 1
```
I have also tried `clang++, g++-8, g++4.8.5`.  All give slightly different errors....

**Comment by rrwick** [comment] 2018-09-05 23:50
That's certainly an odd one! I can't reproduce the issues on my Mac, with either Clang or GCC. I fear this may be specific to your machine 😦 

These issues have a similar smell:
https://github.com/isovic/graphmap/issues/77
https://groups.google.com/forum/#!topic/bedtools-discuss/CURWF19qBuA
Perhaps they can point you in the right direction?

Sorry I can't be of more help (I'm no wizard with this kind of stuff). I'm reasonably sure it isn't related to Unicycler itself, so I'm going to close this issue. But if you disagree (think Unicycler needs to change) - please reopen it!

Ryan

**Closed by rrwick** 2018-09-05 23:50 UTC
