### ISSUE TITLE
Number of threads for spades error correction is limited to 32?

### ISSUE THREAD

**Issue by raw937** [rrwick/Unicycler#208] opened 2019-10-08 18:29 UTC
Hello, 

I have given the assembler -t 60. 

Unicycler version: v0.4.7
Using 60 threads

I noticed that at the error correction step it defaults to 32. 
--threads 32 --only-error-correction

Any way to fix this?

**Comment by stevenjdunn** [comment] 2019-12-03 08:34
I can't reproduce this my end, a few things to check:

Does unicyler.log show the correction command as calling 60 threads? 

Can you run spades in --only-error-correction mode manually with 60 threads?

Do you have ~32 gb of RAM available?

**Comment by raw937** [comment] 2019-12-03 19:47
The log shows 60 threads. 
The command quote within the log shows 32 threads for error correction mode.
I think it is a spades issue. Yes, I have 2 TB of RAM available.

**Comment by tolot27** [comment] 2020-01-21 06:33
I run into the same issue.
Limitting spades to a maximum of 32 threads is hardcoded at https://github.com/rrwick/Unicycler/blob/master/unicycler/spades_func.py#L45.

**Comment by rrwick** [comment] 2022-01-22 04:56
Yes, I deliberately limited SPAdes to 32 threads, as I encountered issues with very high thread counts. Also, I've removed read-error-correction from the Unicycler pipeline in the current version (v0.5.0), so this no longer applies and I'm going to close this issue now.

**Closed by rrwick** 2022-01-22 04:56 UTC

**Comment by raw937** [comment] 2022-01-22 04:59
Why did you remove error correction? What are you using for error correction now? Also, have to tried Ray or other MPP for more threads?

**Comment by tolot27** [comment] 2022-01-22 09:36
> Yes, I deliberately limited SPAdes to 32 threads, as I encountered issues with very high thread counts. Also, I've removed read-error-correction from the Unicycler pipeline in the current version (v0.5.0), so this no longer applies and I'm going to close this issue now.

The issues with high number of threads is related to the memory usage per thread. [SPAdes uses 512 Mb per thread for buffers](https://github.com/ablab/spades#spades-performance). I use `-m 800` with `-t 200` on my 2 TB machine with a MiSeq v3 data set and it runs very well. Hence, I suggest always providing the memory parameter `-m` on thread counts higher than 30.

**Comment by rrwick** [comment] 2022-01-23 02:12
I haven't found that read-error-correction is helpful, especially if you've done some QC (e.g. with [fastp](https://github.com/OpenGene/fastp)) before assembly. And I think it carries the risk of overcorrecting variants in repeats, i.e. introducing errors into the assembly.

SPAdes itself now has an `--isolate` mode designed for whole genome isolate datasets, and this mode also turns off read-error-correction. So I think the SPAdes developers have come to the same conclusion!

Also, the new version of Unicycler (v0.5.0, about to release) has a `--spades_options` option where you can pass things like `-m`, if that helps.

Ryan

**Comment by raw937** [comment] 2022-01-23 02:17
Thanks Ryan! Thoughts on hybrid pacbio-illumina or oxford-illumina?
